package reviewrun

import (
 "context"; "encoding/json"; "fmt"; "os"; "path/filepath"; "sort"; "strings"
 "codea-harness-tools/internal/reviewauthority"
)
var verifySelectionTurn180=reviewauthority.VerifySelectionTurn180
type scopeState180 struct{SchemaVersion int `json:"schemaVersion"`;RunID string `json:"runId"`;OptionsHash string `json:"optionsHash"`;SelectedIDs []string `json:"selectedIds"`;Chains []Chain `json:"chains"`;Reads []ReadRef `json:"reads"`;Coverage string `json:"coverage"`}
func Select(ctx context.Context,root string,req SelectionRequest,turn HostTurn)(Outcome,error){
 if ctx==nil{ctx=context.Background()};if err:=validateRunID(req.RunID);err!=nil{return Outcome{},err};runDir,state,err:=loadRun(root,req.RunID);if err!=nil{return Outcome{},err};if state.Cancelled{return Outcome{},fmt.Errorf("REVIEW_SELECT_CANCELLED")};stored,err:=loadPreparedOptions180(runDir);if err!=nil{return Outcome{},fmt.Errorf("REVIEW_OPTIONS_STALE: %w",err)};if req.OptionsHash==""||req.OptionsHash!=stored.Options.Hash{return Outcome{},fmt.Errorf("REVIEW_OPTIONS_STALE")};rootAbs,_:=filepath.Abs(root);if !sameProjectPath180(stored.ProjectRoot,rootAbs){return Outcome{},fmt.Errorf("REVIEW_OPTIONS_STALE: project changed")};same,err:=sourceSnapshotMatches180(rootAbs,stored.SourcePaths,stored.SourceFingerprint);if err!=nil||!same{return Outcome{},fmt.Errorf("REVIEW_OPTIONS_STALE: source changed")};if !stored.Options.SelectionRequired{return Outcome{},fmt.Errorf("REVIEW_SELECTION_NOT_REQUIRED")}
 ids:=make([]string,0,len(req.IDs));if len(req.IDs)==0{return Outcome{},fmt.Errorf("REVIEW_SELECTION_IDS_REQUIRED")};seen:=map[string]bool{};valid:=map[string]Chain{};allIDs:=[]string{};for _,c:=range stored.Options.Chains{valid[c.ID]=c;allIDs=append(allIDs,c.ID)};selected:=[]Chain{};for _,rawID:=range req.IDs{id:=strings.TrimSpace(rawID);if id==""||seen[id]{return Outcome{},fmt.Errorf("REVIEW_SELECTION_ID_INVALID")};seen[id]=true;c,ok:=valid[id];if !ok{return Outcome{},fmt.Errorf("REVIEW_SELECTION_UNKNOWN_CHAIN: %s",id)};ids=append(ids,id);selected=append(selected,c)};sort.Strings(ids)
 if err:=verifySelectionTurn180(ctx,rootAbs,reviewauthority.SelectionTurnRequest180{SessionID:turn.SessionID,MessageID:turn.MessageID,RunID:req.RunID,OptionsHash:req.OptionsHash,SelectionIDs:ids,AllIDs:allIDs,MenuMarker:selectionMenuMarker180(stored.Options)});err!=nil{return Outcome{},err}
 unlock,err:=acquireRunLock(ctx,runDir);if err!=nil{return Outcome{},err};defer unlock();_,state,err=loadRun(root,req.RunID);if err!=nil{return Outcome{},err};if state.Cancelled{return Outcome{},fmt.Errorf("REVIEW_SELECT_CANCELLED")}
 current,err:=loadPreparedOptions180(runDir);if err!=nil{return Outcome{},fmt.Errorf("REVIEW_OPTIONS_STALE: %w",err)};if current.Options.Hash!=req.OptionsHash||!sameProjectPath180(current.ProjectRoot,rootAbs){return Outcome{},fmt.Errorf("REVIEW_OPTIONS_STALE: options changed")};same,err=sourceSnapshotMatches180(rootAbs,current.SourcePaths,current.SourceFingerprint);if err!=nil||!same{return Outcome{},fmt.Errorf("REVIEW_OPTIONS_STALE: source changed")}
 coverage:="COMPLETE";for _,c:=range selected{if len(c.Unresolved)>0{coverage="PARTIAL";break}};if err:=writeScope180(runDir,req.RunID,req.OptionsHash,ids,selected,rootAbs);err!=nil{return Outcome{},err};same,err=sourceSnapshotMatches180(rootAbs,current.SourcePaths,current.SourceFingerprint);if err!=nil||!same{_ = os.Remove(filepath.Join(runDir,"scope.json"));return Outcome{},fmt.Errorf("REVIEW_OPTIONS_STALE: source changed during selection")};state.SelectedIDs=ids;state.ScopeReady=true;state.Coverage=coverage;state.LastError="";if err:=writeState(runDir,state);err!=nil{return Outcome{},err};return Outcome{RunID:req.RunID,Execution:"INCOMPLETE",ReviewConclusion:"UNDETERMINED",Coverage:coverage,ReportPath:state.ReportPath,ReportSHA256:currentReportSHA180(state.ReportPath)},nil
}
func selectionMenuMarker180(o Options)string{lines:=[]string{};for _,c:=range o.Chains{lines=append(lines,c.ID+" "+c.Name)};return strings.Join(lines,"\n")}
func chainsForIDs180(all []Chain,ids []string)[]Chain{if len(ids)==0{return []Chain{}};s:=map[string]bool{};for _,id:=range ids{s[id]=true};out:=[]Chain{};for _,c:=range all{if s[c.ID]{out=append(out,c)}};return out}
func writeScope180(runDir,runID,hash string,ids []string,chains []Chain,root string)error{reads:=[]ReadRef{};seen:=map[string]bool{};for _,c:=range chains{for _,n:=range c.Nodes{if seen[n.Path]{continue};seen[n.Path]=true;b,e:=os.ReadFile(filepath.Join(root,filepath.FromSlash(n.Path)));if e!=nil{return fmt.Errorf("REVIEW_SCOPE_READ_FAILED: %s: %w",n.Path,e)};lines:=strings.Count(string(b),"\n");if len(b)==0||b[len(b)-1]!='\n'{lines++};if lines<1{lines=1};reads=append(reads,ReadRef{Path:n.Path,SHA256:bytesSHA256(b),StartLine:1,EndLine:lines})}};sort.Slice(reads,func(i,j int)bool{return reads[i].Path<reads[j].Path});coverage:="COMPLETE";for _,c:=range chains{if len(c.Unresolved)>0{coverage="PARTIAL"}};v:=scopeState180{SchemaVersion:SchemaVersion,RunID:runID,OptionsHash:hash,SelectedIDs:append([]string{},ids...),Chains:chains,Reads:reads,Coverage:coverage};b,e:=json.MarshalIndent(v,"","  ");if e!=nil{return e};b=append(b,'\n');if e:=atomicWrite(filepath.Join(runDir,"scope.json"),b);e!=nil{return fmt.Errorf("REVIEW_SCOPE_WRITE_FAILED: %w",e)};return nil}
func currentReportSHA180(path string)string{b,e:=os.ReadFile(path);if e!=nil{return ""};return bytesSHA256(b)}